
INSERT INTO public.news (title, slug, excerpt, content, category, author, status, pinned, is_featured, language, visibility, tags, published_at, department_access) VALUES
  ('Novo Plano de Benefícios 2026', 'novo-plano-beneficios-2026', 'Conheça as mudanças no plano de benefícios que entram em vigor em julho.', '<p>A empresa anuncia um novo pacote de benefícios corporativos com melhorias significativas em saúde, educação e bem-estar.</p>', 'comunicado', 'Recursos Humanos', 'published', true, true, 'pt', 'public', ARRAY['benefícios','rh','2026'], now() - interval '2 days', '{}'),
  ('New Benefits Plan 2026', 'new-benefits-plan-2026', 'Learn about the upcoming changes to the benefits plan effective July.', '<p>The company announces a new corporate benefits package with significant improvements in health, education, and wellness.</p>', 'comunicado', 'Human Resources', 'published', false, true, 'en', 'public', ARRAY['benefits','hr','2026'], now() - interval '2 days', '{}'),
  ('Semana de Inovação — Inscrições Abertas', 'semana-inovacao-inscricoes', 'Participe da Semana de Inovação de 21 a 25 de julho.', '<p>A Semana de Inovação está de volta! Este ano o tema é "IA Responsável no Ambiente Corporativo".</p>', 'evento', 'Diretoria de Tecnologia', 'published', false, true, 'pt', 'public', ARRAY['inovação','evento','tecnologia'], now() - interval '5 days', '{}'),
  ('Alerta: Manutenção nos Sistemas — 19/07', 'manutencao-sistemas-julho', 'Os sistemas internos ficarão indisponíveis das 22h às 6h do dia 19/07.', '<p>Informamos que haverá manutenção programada nos servidores internos.</p>', 'aviso', 'TI Infraestrutura', 'published', true, false, 'pt', 'public', ARRAY['manutenção','ti','sistemas'], now() - interval '1 day', '{}'),
  ('Campanha Solidária — Doe Agasalhos', 'campanha-solidaria-agasalhos', 'Participe da campanha de inverno e ajude quem mais precisa.', '<p>A campanha de arrecadação de agasalhos acontece de 1º a 31 de julho.</p>', 'campanha', 'Comitê Social', 'published', false, false, 'pt', 'public', ARRAY['campanha','social','inverno'], now() - interval '7 days', '{}'),
  ('Resultados Q2 — Apresentação Diretoria', 'resultados-q2-diretoria', 'Resumo dos resultados do segundo trimestre e metas para Q3.', '<p>A apresentação dos resultados do Q2 será realizada na próxima sexta-feira.</p>', 'comunicado', 'Diretoria Financeira', 'draft', false, false, 'pt', 'department', ARRAY['financeiro','resultados'], NULL, ARRAY['financeiro']),
  ('Política de Trabalho Remoto — Atualização', 'politica-trabalho-remoto', 'Novas diretrizes para o modelo híbrido a partir de agosto.', '<p>A política de trabalho remoto foi revisada com flexibilização dos dias presenciais.</p>', 'comunicado', 'Recursos Humanos', 'review', false, false, 'pt', 'public', ARRAY['rh','remoto','política'], NULL, '{}'),
  ('Company Town Hall — Q3 Kickoff', 'company-town-hall-q3', 'Join us for the Q3 kickoff town hall meeting on August 5th.', '<p>Our quarterly town hall will cover Q2 results, Q3 goals, and strategic initiatives.</p>', 'evento', 'Executive Office', 'published', false, false, 'en', 'public', ARRAY['town-hall','q3'], now() - interval '3 days', '{}')
ON CONFLICT DO NOTHING;
