/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProcedimentosRouteImport } from './routes/_authenticated/procedimentos'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated/noticias'
import { Route as AuthenticatedInstitucionalRouteImport } from './routes/_authenticated/institucional'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDepartamentosRouteImport } from './routes/_authenticated/departamentos'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProcedimentosSlugRouteImport } from './routes/_authenticated/procedimentos.$slug'
import { Route as AuthenticatedNoticiasSlugRouteImport } from './routes/_authenticated/noticias.$slug'
import { Route as AuthenticatedInstitucionalSlugRouteImport } from './routes/_authenticated/institucional.$slug'
import { Route as AuthenticatedDocumentosSlugRouteImport } from './routes/_authenticated/documentos.$slug'
import { Route as AuthenticatedDepartamentoSlugRouteImport } from './routes/_authenticated/departamento.$slug'
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcedimentosRoute =
  AuthenticatedProcedimentosRouteImport.update({
    id: '/procedimentos',
    path: '/procedimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstitucionalRoute =
  AuthenticatedInstitucionalRouteImport.update({
    id: '/institucional',
    path: '/institucional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartamentosRoute =
  AuthenticatedDepartamentosRouteImport.update({
    id: '/departamentos',
    path: '/departamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcedimentosSlugRoute =
  AuthenticatedProcedimentosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedProcedimentosRoute,
  } as any)
const AuthenticatedNoticiasSlugRoute =
  AuthenticatedNoticiasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedNoticiasRoute,
  } as any)
const AuthenticatedInstitucionalSlugRoute =
  AuthenticatedInstitucionalSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedInstitucionalRoute,
  } as any)
const AuthenticatedDocumentosSlugRoute =
  AuthenticatedDocumentosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)
const AuthenticatedDepartamentoSlugRoute =
  AuthenticatedDepartamentoSlugRouteImport.update({
    id: '/departamento/$slug',
    path: '/departamento/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedColaboradoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/departamentos': typeof AuthenticatedDepartamentosRoute
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/institucional': typeof AuthenticatedInstitucionalRouteWithChildren
  '/noticias': typeof AuthenticatedNoticiasRouteWithChildren
  '/procedimentos': typeof AuthenticatedProcedimentosRouteWithChildren
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/departamento/$slug': typeof AuthenticatedDepartamentoSlugRoute
  '/documentos/$slug': typeof AuthenticatedDocumentosSlugRoute
  '/institucional/$slug': typeof AuthenticatedInstitucionalSlugRoute
  '/noticias/$slug': typeof AuthenticatedNoticiasSlugRoute
  '/procedimentos/$slug': typeof AuthenticatedProcedimentosSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/departamentos': typeof AuthenticatedDepartamentosRoute
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/institucional': typeof AuthenticatedInstitucionalRouteWithChildren
  '/noticias': typeof AuthenticatedNoticiasRouteWithChildren
  '/procedimentos': typeof AuthenticatedProcedimentosRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/departamento/$slug': typeof AuthenticatedDepartamentoSlugRoute
  '/documentos/$slug': typeof AuthenticatedDocumentosSlugRoute
  '/institucional/$slug': typeof AuthenticatedInstitucionalSlugRoute
  '/noticias/$slug': typeof AuthenticatedNoticiasSlugRoute
  '/procedimentos/$slug': typeof AuthenticatedProcedimentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/_authenticated/departamentos': typeof AuthenticatedDepartamentosRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/_authenticated/institucional': typeof AuthenticatedInstitucionalRouteWithChildren
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRouteWithChildren
  '/_authenticated/procedimentos': typeof AuthenticatedProcedimentosRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/_authenticated/departamento/$slug': typeof AuthenticatedDepartamentoSlugRoute
  '/_authenticated/documentos/$slug': typeof AuthenticatedDocumentosSlugRoute
  '/_authenticated/institucional/$slug': typeof AuthenticatedInstitucionalSlugRoute
  '/_authenticated/noticias/$slug': typeof AuthenticatedNoticiasSlugRoute
  '/_authenticated/procedimentos/$slug': typeof AuthenticatedProcedimentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/colaboradores'
    | '/departamentos'
    | '/documentos'
    | '/institucional'
    | '/noticias'
    | '/procedimentos'
    | '/colaboradores/$id'
    | '/departamento/$slug'
    | '/documentos/$slug'
    | '/institucional/$slug'
    | '/noticias/$slug'
    | '/procedimentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/colaboradores'
    | '/departamentos'
    | '/documentos'
    | '/institucional'
    | '/noticias'
    | '/procedimentos'
    | '/'
    | '/colaboradores/$id'
    | '/departamento/$slug'
    | '/documentos/$slug'
    | '/institucional/$slug'
    | '/noticias/$slug'
    | '/procedimentos/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/colaboradores'
    | '/_authenticated/departamentos'
    | '/_authenticated/documentos'
    | '/_authenticated/institucional'
    | '/_authenticated/noticias'
    | '/_authenticated/procedimentos'
    | '/_authenticated/'
    | '/_authenticated/colaboradores/$id'
    | '/_authenticated/departamento/$slug'
    | '/_authenticated/documentos/$slug'
    | '/_authenticated/institucional/$slug'
    | '/_authenticated/noticias/$slug'
    | '/_authenticated/procedimentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procedimentos': {
      id: '/_authenticated/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof AuthenticatedProcedimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/institucional': {
      id: '/_authenticated/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof AuthenticatedInstitucionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departamentos': {
      id: '/_authenticated/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof AuthenticatedDepartamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procedimentos/$slug': {
      id: '/_authenticated/procedimentos/$slug'
      path: '/$slug'
      fullPath: '/procedimentos/$slug'
      preLoaderRoute: typeof AuthenticatedProcedimentosSlugRouteImport
      parentRoute: typeof AuthenticatedProcedimentosRoute
    }
    '/_authenticated/noticias/$slug': {
      id: '/_authenticated/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof AuthenticatedNoticiasSlugRouteImport
      parentRoute: typeof AuthenticatedNoticiasRoute
    }
    '/_authenticated/institucional/$slug': {
      id: '/_authenticated/institucional/$slug'
      path: '/$slug'
      fullPath: '/institucional/$slug'
      preLoaderRoute: typeof AuthenticatedInstitucionalSlugRouteImport
      parentRoute: typeof AuthenticatedInstitucionalRoute
    }
    '/_authenticated/documentos/$slug': {
      id: '/_authenticated/documentos/$slug'
      path: '/$slug'
      fullPath: '/documentos/$slug'
      preLoaderRoute: typeof AuthenticatedDocumentosSlugRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
    '/_authenticated/departamento/$slug': {
      id: '/_authenticated/departamento/$slug'
      path: '/departamento/$slug'
      fullPath: '/departamento/$slug'
      preLoaderRoute: typeof AuthenticatedDepartamentoSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedColaboradoresRoute
    }
  }
}

interface AuthenticatedColaboradoresRouteChildren {
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
}

const AuthenticatedColaboradoresRouteChildren: AuthenticatedColaboradoresRouteChildren =
  {
    AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
  }

const AuthenticatedColaboradoresRouteWithChildren =
  AuthenticatedColaboradoresRoute._addFileChildren(
    AuthenticatedColaboradoresRouteChildren,
  )

interface AuthenticatedDocumentosRouteChildren {
  AuthenticatedDocumentosSlugRoute: typeof AuthenticatedDocumentosSlugRoute
}

const AuthenticatedDocumentosRouteChildren: AuthenticatedDocumentosRouteChildren =
  {
    AuthenticatedDocumentosSlugRoute: AuthenticatedDocumentosSlugRoute,
  }

const AuthenticatedDocumentosRouteWithChildren =
  AuthenticatedDocumentosRoute._addFileChildren(
    AuthenticatedDocumentosRouteChildren,
  )

interface AuthenticatedInstitucionalRouteChildren {
  AuthenticatedInstitucionalSlugRoute: typeof AuthenticatedInstitucionalSlugRoute
}

const AuthenticatedInstitucionalRouteChildren: AuthenticatedInstitucionalRouteChildren =
  {
    AuthenticatedInstitucionalSlugRoute: AuthenticatedInstitucionalSlugRoute,
  }

const AuthenticatedInstitucionalRouteWithChildren =
  AuthenticatedInstitucionalRoute._addFileChildren(
    AuthenticatedInstitucionalRouteChildren,
  )

interface AuthenticatedNoticiasRouteChildren {
  AuthenticatedNoticiasSlugRoute: typeof AuthenticatedNoticiasSlugRoute
}

const AuthenticatedNoticiasRouteChildren: AuthenticatedNoticiasRouteChildren = {
  AuthenticatedNoticiasSlugRoute: AuthenticatedNoticiasSlugRoute,
}

const AuthenticatedNoticiasRouteWithChildren =
  AuthenticatedNoticiasRoute._addFileChildren(
    AuthenticatedNoticiasRouteChildren,
  )

interface AuthenticatedProcedimentosRouteChildren {
  AuthenticatedProcedimentosSlugRoute: typeof AuthenticatedProcedimentosSlugRoute
}

const AuthenticatedProcedimentosRouteChildren: AuthenticatedProcedimentosRouteChildren =
  {
    AuthenticatedProcedimentosSlugRoute: AuthenticatedProcedimentosSlugRoute,
  }

const AuthenticatedProcedimentosRouteWithChildren =
  AuthenticatedProcedimentosRoute._addFileChildren(
    AuthenticatedProcedimentosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRouteWithChildren
  AuthenticatedDepartamentosRoute: typeof AuthenticatedDepartamentosRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRouteWithChildren
  AuthenticatedInstitucionalRoute: typeof AuthenticatedInstitucionalRouteWithChildren
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRouteWithChildren
  AuthenticatedProcedimentosRoute: typeof AuthenticatedProcedimentosRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDepartamentoSlugRoute: typeof AuthenticatedDepartamentoSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRouteWithChildren,
  AuthenticatedDepartamentosRoute: AuthenticatedDepartamentosRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRouteWithChildren,
  AuthenticatedInstitucionalRoute: AuthenticatedInstitucionalRouteWithChildren,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRouteWithChildren,
  AuthenticatedProcedimentosRoute: AuthenticatedProcedimentosRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDepartamentoSlugRoute: AuthenticatedDepartamentoSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
