/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SrcRoutes_rootRouteImport } from './routes/src/routes/__root'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstitucionalRouteImport } from './routes/institucional'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProcedimentosRouteImport } from './routes/_authenticated/procedimentos'
import { Route as AuthenticatedNoticiasRouteImport } from './routes/_authenticated/noticias'
import { Route as AuthenticatedInstitucionalRouteImport } from './routes/_authenticated/institucional'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDepartamentosRouteImport } from './routes/_authenticated/departamentos'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SrcRoutesLoginRouteImport } from './routes/src/routes/login'
import { Route as SrcRoutesAuthenticatedRouteImport } from './routes/src/routes/_authenticated'
import { Route as AuthenticatedProcedimentosSlugRouteImport } from './routes/_authenticated/procedimentos.$slug'
import { Route as AuthenticatedNoticiasSlugRouteImport } from './routes/_authenticated/noticias.$slug'
import { Route as AuthenticatedInstitucionalSlugRouteImport } from './routes/_authenticated/institucional.$slug'
import { Route as AuthenticatedDocumentosSlugRouteImport } from './routes/_authenticated/documentos.$slug'
import { Route as AuthenticatedDepartamentoSlugRouteImport } from './routes/_authenticated/departamento.$slug'
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores.$id'
import { Route as SrcRoutesAuthenticatedIndexRouteImport } from './routes/src/routes/_authenticated/index'
import { Route as SrcRoutesAuthenticatedProcedimentosRouteImport } from './routes/src/routes/_authenticated/procedimentos'
import { Route as SrcRoutesAuthenticatedNoticiasRouteImport } from './routes/src/routes/_authenticated/noticias'
import { Route as SrcRoutesAuthenticatedInstitucionalRouteImport } from './routes/src/routes/_authenticated/institucional'
import { Route as SrcRoutesAuthenticatedDocumentosRouteImport } from './routes/src/routes/_authenticated/documentos'
import { Route as SrcRoutesAuthenticatedDepartamentosRouteImport } from './routes/src/routes/_authenticated/departamentos'
import { Route as SrcRoutesAuthenticatedColaboradoresRouteImport } from './routes/src/routes/_authenticated/colaboradores'
import { Route as SrcRoutesAuthenticatedAdminRouteImport } from './routes/src/routes/_authenticated/admin'
import { Route as SrcRoutesAuthenticatedProcedimentosSlugRouteImport } from './routes/src/routes/_authenticated/procedimentos.$slug'
import { Route as SrcRoutesAuthenticatedNoticiasSlugRouteImport } from './routes/src/routes/_authenticated/noticias.$slug'
import { Route as SrcRoutesAuthenticatedInstitucionalSlugRouteImport } from './routes/src/routes/_authenticated/institucional.$slug'
import { Route as SrcRoutesAuthenticatedDocumentosSlugRouteImport } from './routes/src/routes/_authenticated/documentos.$slug'
import { Route as SrcRoutesAuthenticatedDepartamentoSlugRouteImport } from './routes/src/routes/_authenticated/departamento.$slug'
import { Route as SrcRoutesAuthenticatedColaboradoresIdRouteImport } from './routes/src/routes/_authenticated/colaboradores.$id'

const SrcRoutes_rootRoute = SrcRoutes_rootRouteImport.update({
  id: '/src/routes/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitucionalRoute = InstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcedimentosRoute =
  AuthenticatedProcedimentosRouteImport.update({
    id: '/procedimentos',
    path: '/procedimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNoticiasRoute = AuthenticatedNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstitucionalRoute =
  AuthenticatedInstitucionalRouteImport.update({
    id: '/institucional',
    path: '/institucional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartamentosRoute =
  AuthenticatedDepartamentosRouteImport.update({
    id: '/departamentos',
    path: '/departamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SrcRoutesLoginRoute = SrcRoutesLoginRouteImport.update({
  id: '/src/routes/login',
  path: '/src/routes/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SrcRoutesAuthenticatedRoute = SrcRoutesAuthenticatedRouteImport.update({
  id: '/src/routes/_authenticated',
  path: '/src/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProcedimentosSlugRoute =
  AuthenticatedProcedimentosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedProcedimentosRoute,
  } as any)
const AuthenticatedNoticiasSlugRoute =
  AuthenticatedNoticiasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedNoticiasRoute,
  } as any)
const AuthenticatedInstitucionalSlugRoute =
  AuthenticatedInstitucionalSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedInstitucionalRoute,
  } as any)
const AuthenticatedDocumentosSlugRoute =
  AuthenticatedDocumentosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)
const AuthenticatedDepartamentoSlugRoute =
  AuthenticatedDepartamentoSlugRouteImport.update({
    id: '/departamento/$slug',
    path: '/departamento/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedColaboradoresRoute,
  } as any)
const SrcRoutesAuthenticatedIndexRoute =
  SrcRoutesAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedProcedimentosRoute =
  SrcRoutesAuthenticatedProcedimentosRouteImport.update({
    id: '/procedimentos',
    path: '/procedimentos',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedNoticiasRoute =
  SrcRoutesAuthenticatedNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedInstitucionalRoute =
  SrcRoutesAuthenticatedInstitucionalRouteImport.update({
    id: '/institucional',
    path: '/institucional',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedDocumentosRoute =
  SrcRoutesAuthenticatedDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedDepartamentosRoute =
  SrcRoutesAuthenticatedDepartamentosRouteImport.update({
    id: '/departamentos',
    path: '/departamentos',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedColaboradoresRoute =
  SrcRoutesAuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedAdminRoute =
  SrcRoutesAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedProcedimentosSlugRoute =
  SrcRoutesAuthenticatedProcedimentosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => SrcRoutesAuthenticatedProcedimentosRoute,
  } as any)
const SrcRoutesAuthenticatedNoticiasSlugRoute =
  SrcRoutesAuthenticatedNoticiasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => SrcRoutesAuthenticatedNoticiasRoute,
  } as any)
const SrcRoutesAuthenticatedInstitucionalSlugRoute =
  SrcRoutesAuthenticatedInstitucionalSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => SrcRoutesAuthenticatedInstitucionalRoute,
  } as any)
const SrcRoutesAuthenticatedDocumentosSlugRoute =
  SrcRoutesAuthenticatedDocumentosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => SrcRoutesAuthenticatedDocumentosRoute,
  } as any)
const SrcRoutesAuthenticatedDepartamentoSlugRoute =
  SrcRoutesAuthenticatedDepartamentoSlugRouteImport.update({
    id: '/departamento/$slug',
    path: '/departamento/$slug',
    getParentRoute: () => SrcRoutesAuthenticatedRoute,
  } as any)
const SrcRoutesAuthenticatedColaboradoresIdRoute =
  SrcRoutesAuthenticatedColaboradoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => SrcRoutesAuthenticatedColaboradoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/institucional': typeof AuthenticatedInstitucionalRouteWithChildren
  '/login': typeof LoginRoute
  '/noticias': typeof AuthenticatedNoticiasRouteWithChildren
  '/procedimentos': typeof AuthenticatedProcedimentosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/departamentos': typeof AuthenticatedDepartamentosRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/departamento/$slug': typeof AuthenticatedDepartamentoSlugRoute
  '/documentos/$slug': typeof AuthenticatedDocumentosSlugRoute
  '/institucional/$slug': typeof AuthenticatedInstitucionalSlugRoute
  '/noticias/$slug': typeof AuthenticatedNoticiasSlugRoute
  '/procedimentos/$slug': typeof AuthenticatedProcedimentosSlugRoute
  '/src/routes': typeof SrcRoutesAuthenticatedRouteWithChildren
  '/src/routes/login': typeof SrcRoutesLoginRoute
  '/src/routes/admin': typeof SrcRoutesAuthenticatedAdminRoute
  '/src/routes/colaboradores': typeof SrcRoutesAuthenticatedColaboradoresRouteWithChildren
  '/src/routes/departamentos': typeof SrcRoutesAuthenticatedDepartamentosRoute
  '/src/routes/documentos': typeof SrcRoutesAuthenticatedDocumentosRouteWithChildren
  '/src/routes/institucional': typeof SrcRoutesAuthenticatedInstitucionalRouteWithChildren
  '/src/routes/noticias': typeof SrcRoutesAuthenticatedNoticiasRouteWithChildren
  '/src/routes/procedimentos': typeof SrcRoutesAuthenticatedProcedimentosRouteWithChildren
  '/src/routes/': typeof SrcRoutesAuthenticatedIndexRoute
  '/src/routes/colaboradores/$id': typeof SrcRoutesAuthenticatedColaboradoresIdRoute
  '/src/routes/departamento/$slug': typeof SrcRoutesAuthenticatedDepartamentoSlugRoute
  '/src/routes/documentos/$slug': typeof SrcRoutesAuthenticatedDocumentosSlugRoute
  '/src/routes/institucional/$slug': typeof SrcRoutesAuthenticatedInstitucionalSlugRoute
  '/src/routes/noticias/$slug': typeof SrcRoutesAuthenticatedNoticiasSlugRoute
  '/src/routes/procedimentos/$slug': typeof SrcRoutesAuthenticatedProcedimentosSlugRoute
}
export interface FileRoutesByTo {
  '/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/institucional': typeof AuthenticatedInstitucionalRouteWithChildren
  '/login': typeof LoginRoute
  '/noticias': typeof AuthenticatedNoticiasRouteWithChildren
  '/procedimentos': typeof AuthenticatedProcedimentosRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/departamentos': typeof AuthenticatedDepartamentosRoute
  '/': typeof AuthenticatedIndexRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/departamento/$slug': typeof AuthenticatedDepartamentoSlugRoute
  '/documentos/$slug': typeof AuthenticatedDocumentosSlugRoute
  '/institucional/$slug': typeof AuthenticatedInstitucionalSlugRoute
  '/noticias/$slug': typeof AuthenticatedNoticiasSlugRoute
  '/procedimentos/$slug': typeof AuthenticatedProcedimentosSlugRoute
  '/src/routes': typeof SrcRoutesAuthenticatedIndexRoute
  '/src/routes/login': typeof SrcRoutesLoginRoute
  '/src/routes/admin': typeof SrcRoutesAuthenticatedAdminRoute
  '/src/routes/colaboradores': typeof SrcRoutesAuthenticatedColaboradoresRouteWithChildren
  '/src/routes/departamentos': typeof SrcRoutesAuthenticatedDepartamentosRoute
  '/src/routes/documentos': typeof SrcRoutesAuthenticatedDocumentosRouteWithChildren
  '/src/routes/institucional': typeof SrcRoutesAuthenticatedInstitucionalRouteWithChildren
  '/src/routes/noticias': typeof SrcRoutesAuthenticatedNoticiasRouteWithChildren
  '/src/routes/procedimentos': typeof SrcRoutesAuthenticatedProcedimentosRouteWithChildren
  '/src/routes/colaboradores/$id': typeof SrcRoutesAuthenticatedColaboradoresIdRoute
  '/src/routes/departamento/$slug': typeof SrcRoutesAuthenticatedDepartamentoSlugRoute
  '/src/routes/documentos/$slug': typeof SrcRoutesAuthenticatedDocumentosSlugRoute
  '/src/routes/institucional/$slug': typeof SrcRoutesAuthenticatedInstitucionalSlugRoute
  '/src/routes/noticias/$slug': typeof SrcRoutesAuthenticatedNoticiasSlugRoute
  '/src/routes/procedimentos/$slug': typeof SrcRoutesAuthenticatedProcedimentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/colaboradores': typeof ColaboradoresRoute
  '/documentos': typeof DocumentosRoute
  '/institucional': typeof InstitucionalRoute
  '/login': typeof LoginRoute
  '/noticias': typeof NoticiasRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRouteWithChildren
  '/_authenticated/departamentos': typeof AuthenticatedDepartamentosRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/_authenticated/institucional': typeof AuthenticatedInstitucionalRouteWithChildren
  '/_authenticated/noticias': typeof AuthenticatedNoticiasRouteWithChildren
  '/_authenticated/procedimentos': typeof AuthenticatedProcedimentosRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/_authenticated/departamento/$slug': typeof AuthenticatedDepartamentoSlugRoute
  '/_authenticated/documentos/$slug': typeof AuthenticatedDocumentosSlugRoute
  '/_authenticated/institucional/$slug': typeof AuthenticatedInstitucionalSlugRoute
  '/_authenticated/noticias/$slug': typeof AuthenticatedNoticiasSlugRoute
  '/_authenticated/procedimentos/$slug': typeof AuthenticatedProcedimentosSlugRoute
  '/src/routes/__root': typeof SrcRoutes_rootRoute
  '/src/routes/_authenticated': typeof SrcRoutesAuthenticatedRouteWithChildren
  '/src/routes/login': typeof SrcRoutesLoginRoute
  '/src/routes/_authenticated/admin': typeof SrcRoutesAuthenticatedAdminRoute
  '/src/routes/_authenticated/colaboradores': typeof SrcRoutesAuthenticatedColaboradoresRouteWithChildren
  '/src/routes/_authenticated/departamentos': typeof SrcRoutesAuthenticatedDepartamentosRoute
  '/src/routes/_authenticated/documentos': typeof SrcRoutesAuthenticatedDocumentosRouteWithChildren
  '/src/routes/_authenticated/institucional': typeof SrcRoutesAuthenticatedInstitucionalRouteWithChildren
  '/src/routes/_authenticated/noticias': typeof SrcRoutesAuthenticatedNoticiasRouteWithChildren
  '/src/routes/_authenticated/procedimentos': typeof SrcRoutesAuthenticatedProcedimentosRouteWithChildren
  '/src/routes/_authenticated/': typeof SrcRoutesAuthenticatedIndexRoute
  '/src/routes/_authenticated/colaboradores/$id': typeof SrcRoutesAuthenticatedColaboradoresIdRoute
  '/src/routes/_authenticated/departamento/$slug': typeof SrcRoutesAuthenticatedDepartamentoSlugRoute
  '/src/routes/_authenticated/documentos/$slug': typeof SrcRoutesAuthenticatedDocumentosSlugRoute
  '/src/routes/_authenticated/institucional/$slug': typeof SrcRoutesAuthenticatedInstitucionalSlugRoute
  '/src/routes/_authenticated/noticias/$slug': typeof SrcRoutesAuthenticatedNoticiasSlugRoute
  '/src/routes/_authenticated/procedimentos/$slug': typeof SrcRoutesAuthenticatedProcedimentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colaboradores'
    | '/documentos'
    | '/institucional'
    | '/login'
    | '/noticias'
    | '/procedimentos'
    | '/admin'
    | '/departamentos'
    | '/colaboradores/$id'
    | '/departamento/$slug'
    | '/documentos/$slug'
    | '/institucional/$slug'
    | '/noticias/$slug'
    | '/procedimentos/$slug'
    | '/src/routes'
    | '/src/routes/login'
    | '/src/routes/admin'
    | '/src/routes/colaboradores'
    | '/src/routes/departamentos'
    | '/src/routes/documentos'
    | '/src/routes/institucional'
    | '/src/routes/noticias'
    | '/src/routes/procedimentos'
    | '/src/routes/'
    | '/src/routes/colaboradores/$id'
    | '/src/routes/departamento/$slug'
    | '/src/routes/documentos/$slug'
    | '/src/routes/institucional/$slug'
    | '/src/routes/noticias/$slug'
    | '/src/routes/procedimentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/colaboradores'
    | '/documentos'
    | '/institucional'
    | '/login'
    | '/noticias'
    | '/procedimentos'
    | '/admin'
    | '/departamentos'
    | '/'
    | '/colaboradores/$id'
    | '/departamento/$slug'
    | '/documentos/$slug'
    | '/institucional/$slug'
    | '/noticias/$slug'
    | '/procedimentos/$slug'
    | '/src/routes'
    | '/src/routes/login'
    | '/src/routes/admin'
    | '/src/routes/colaboradores'
    | '/src/routes/departamentos'
    | '/src/routes/documentos'
    | '/src/routes/institucional'
    | '/src/routes/noticias'
    | '/src/routes/procedimentos'
    | '/src/routes/colaboradores/$id'
    | '/src/routes/departamento/$slug'
    | '/src/routes/documentos/$slug'
    | '/src/routes/institucional/$slug'
    | '/src/routes/noticias/$slug'
    | '/src/routes/procedimentos/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/colaboradores'
    | '/documentos'
    | '/institucional'
    | '/login'
    | '/noticias'
    | '/procedimentos'
    | '/_authenticated/admin'
    | '/_authenticated/colaboradores'
    | '/_authenticated/departamentos'
    | '/_authenticated/documentos'
    | '/_authenticated/institucional'
    | '/_authenticated/noticias'
    | '/_authenticated/procedimentos'
    | '/_authenticated/'
    | '/_authenticated/colaboradores/$id'
    | '/_authenticated/departamento/$slug'
    | '/_authenticated/documentos/$slug'
    | '/_authenticated/institucional/$slug'
    | '/_authenticated/noticias/$slug'
    | '/_authenticated/procedimentos/$slug'
    | '/src/routes/__root'
    | '/src/routes/_authenticated'
    | '/src/routes/login'
    | '/src/routes/_authenticated/admin'
    | '/src/routes/_authenticated/colaboradores'
    | '/src/routes/_authenticated/departamentos'
    | '/src/routes/_authenticated/documentos'
    | '/src/routes/_authenticated/institucional'
    | '/src/routes/_authenticated/noticias'
    | '/src/routes/_authenticated/procedimentos'
    | '/src/routes/_authenticated/'
    | '/src/routes/_authenticated/colaboradores/$id'
    | '/src/routes/_authenticated/departamento/$slug'
    | '/src/routes/_authenticated/documentos/$slug'
    | '/src/routes/_authenticated/institucional/$slug'
    | '/src/routes/_authenticated/noticias/$slug'
    | '/src/routes/_authenticated/procedimentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ColaboradoresRoute: typeof ColaboradoresRoute
  DocumentosRoute: typeof DocumentosRoute
  InstitucionalRoute: typeof InstitucionalRoute
  LoginRoute: typeof LoginRoute
  NoticiasRoute: typeof NoticiasRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  SrcRoutes_rootRoute: typeof SrcRoutes_rootRoute
  SrcRoutesAuthenticatedRoute: typeof SrcRoutesAuthenticatedRouteWithChildren
  SrcRoutesLoginRoute: typeof SrcRoutesLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/src/routes/__root': {
      id: '/src/routes/__root'
      path: '/src/routes'
      fullPath: '/src/routes'
      preLoaderRoute: typeof SrcRoutes_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institucional': {
      id: '/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof InstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/procedimentos': {
      id: '/_authenticated/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof AuthenticatedProcedimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/noticias': {
      id: '/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof AuthenticatedNoticiasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/institucional': {
      id: '/_authenticated/institucional'
      path: '/institucional'
      fullPath: '/institucional'
      preLoaderRoute: typeof AuthenticatedInstitucionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departamentos': {
      id: '/_authenticated/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof AuthenticatedDepartamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/src/routes/login': {
      id: '/src/routes/login'
      path: '/src/routes/login'
      fullPath: '/src/routes/login'
      preLoaderRoute: typeof SrcRoutesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/src/routes/_authenticated': {
      id: '/src/routes/_authenticated'
      path: '/src/routes'
      fullPath: '/src/routes'
      preLoaderRoute: typeof SrcRoutesAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/procedimentos/$slug': {
      id: '/_authenticated/procedimentos/$slug'
      path: '/$slug'
      fullPath: '/procedimentos/$slug'
      preLoaderRoute: typeof AuthenticatedProcedimentosSlugRouteImport
      parentRoute: typeof AuthenticatedProcedimentosRoute
    }
    '/_authenticated/noticias/$slug': {
      id: '/_authenticated/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof AuthenticatedNoticiasSlugRouteImport
      parentRoute: typeof AuthenticatedNoticiasRoute
    }
    '/_authenticated/institucional/$slug': {
      id: '/_authenticated/institucional/$slug'
      path: '/$slug'
      fullPath: '/institucional/$slug'
      preLoaderRoute: typeof AuthenticatedInstitucionalSlugRouteImport
      parentRoute: typeof AuthenticatedInstitucionalRoute
    }
    '/_authenticated/documentos/$slug': {
      id: '/_authenticated/documentos/$slug'
      path: '/$slug'
      fullPath: '/documentos/$slug'
      preLoaderRoute: typeof AuthenticatedDocumentosSlugRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
    '/_authenticated/departamento/$slug': {
      id: '/_authenticated/departamento/$slug'
      path: '/departamento/$slug'
      fullPath: '/departamento/$slug'
      preLoaderRoute: typeof AuthenticatedDepartamentoSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedColaboradoresRoute
    }
    '/src/routes/_authenticated/': {
      id: '/src/routes/_authenticated/'
      path: '/'
      fullPath: '/src/routes/'
      preLoaderRoute: typeof SrcRoutesAuthenticatedIndexRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/procedimentos': {
      id: '/src/routes/_authenticated/procedimentos'
      path: '/procedimentos'
      fullPath: '/src/routes/procedimentos'
      preLoaderRoute: typeof SrcRoutesAuthenticatedProcedimentosRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/noticias': {
      id: '/src/routes/_authenticated/noticias'
      path: '/noticias'
      fullPath: '/src/routes/noticias'
      preLoaderRoute: typeof SrcRoutesAuthenticatedNoticiasRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/institucional': {
      id: '/src/routes/_authenticated/institucional'
      path: '/institucional'
      fullPath: '/src/routes/institucional'
      preLoaderRoute: typeof SrcRoutesAuthenticatedInstitucionalRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/documentos': {
      id: '/src/routes/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/src/routes/documentos'
      preLoaderRoute: typeof SrcRoutesAuthenticatedDocumentosRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/departamentos': {
      id: '/src/routes/_authenticated/departamentos'
      path: '/departamentos'
      fullPath: '/src/routes/departamentos'
      preLoaderRoute: typeof SrcRoutesAuthenticatedDepartamentosRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/colaboradores': {
      id: '/src/routes/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/src/routes/colaboradores'
      preLoaderRoute: typeof SrcRoutesAuthenticatedColaboradoresRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/admin': {
      id: '/src/routes/_authenticated/admin'
      path: '/admin'
      fullPath: '/src/routes/admin'
      preLoaderRoute: typeof SrcRoutesAuthenticatedAdminRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/procedimentos/$slug': {
      id: '/src/routes/_authenticated/procedimentos/$slug'
      path: '/$slug'
      fullPath: '/src/routes/procedimentos/$slug'
      preLoaderRoute: typeof SrcRoutesAuthenticatedProcedimentosSlugRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedProcedimentosRoute
    }
    '/src/routes/_authenticated/noticias/$slug': {
      id: '/src/routes/_authenticated/noticias/$slug'
      path: '/$slug'
      fullPath: '/src/routes/noticias/$slug'
      preLoaderRoute: typeof SrcRoutesAuthenticatedNoticiasSlugRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedNoticiasRoute
    }
    '/src/routes/_authenticated/institucional/$slug': {
      id: '/src/routes/_authenticated/institucional/$slug'
      path: '/$slug'
      fullPath: '/src/routes/institucional/$slug'
      preLoaderRoute: typeof SrcRoutesAuthenticatedInstitucionalSlugRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedInstitucionalRoute
    }
    '/src/routes/_authenticated/documentos/$slug': {
      id: '/src/routes/_authenticated/documentos/$slug'
      path: '/$slug'
      fullPath: '/src/routes/documentos/$slug'
      preLoaderRoute: typeof SrcRoutesAuthenticatedDocumentosSlugRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedDocumentosRoute
    }
    '/src/routes/_authenticated/departamento/$slug': {
      id: '/src/routes/_authenticated/departamento/$slug'
      path: '/departamento/$slug'
      fullPath: '/src/routes/departamento/$slug'
      preLoaderRoute: typeof SrcRoutesAuthenticatedDepartamentoSlugRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedRoute
    }
    '/src/routes/_authenticated/colaboradores/$id': {
      id: '/src/routes/_authenticated/colaboradores/$id'
      path: '/$id'
      fullPath: '/src/routes/colaboradores/$id'
      preLoaderRoute: typeof SrcRoutesAuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof SrcRoutesAuthenticatedColaboradoresRoute
    }
  }
}

interface AuthenticatedColaboradoresRouteChildren {
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
}

const AuthenticatedColaboradoresRouteChildren: AuthenticatedColaboradoresRouteChildren =
  {
    AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
  }

const AuthenticatedColaboradoresRouteWithChildren =
  AuthenticatedColaboradoresRoute._addFileChildren(
    AuthenticatedColaboradoresRouteChildren,
  )

interface AuthenticatedDocumentosRouteChildren {
  AuthenticatedDocumentosSlugRoute: typeof AuthenticatedDocumentosSlugRoute
}

const AuthenticatedDocumentosRouteChildren: AuthenticatedDocumentosRouteChildren =
  {
    AuthenticatedDocumentosSlugRoute: AuthenticatedDocumentosSlugRoute,
  }

const AuthenticatedDocumentosRouteWithChildren =
  AuthenticatedDocumentosRoute._addFileChildren(
    AuthenticatedDocumentosRouteChildren,
  )

interface AuthenticatedInstitucionalRouteChildren {
  AuthenticatedInstitucionalSlugRoute: typeof AuthenticatedInstitucionalSlugRoute
}

const AuthenticatedInstitucionalRouteChildren: AuthenticatedInstitucionalRouteChildren =
  {
    AuthenticatedInstitucionalSlugRoute: AuthenticatedInstitucionalSlugRoute,
  }

const AuthenticatedInstitucionalRouteWithChildren =
  AuthenticatedInstitucionalRoute._addFileChildren(
    AuthenticatedInstitucionalRouteChildren,
  )

interface AuthenticatedNoticiasRouteChildren {
  AuthenticatedNoticiasSlugRoute: typeof AuthenticatedNoticiasSlugRoute
}

const AuthenticatedNoticiasRouteChildren: AuthenticatedNoticiasRouteChildren = {
  AuthenticatedNoticiasSlugRoute: AuthenticatedNoticiasSlugRoute,
}

const AuthenticatedNoticiasRouteWithChildren =
  AuthenticatedNoticiasRoute._addFileChildren(
    AuthenticatedNoticiasRouteChildren,
  )

interface AuthenticatedProcedimentosRouteChildren {
  AuthenticatedProcedimentosSlugRoute: typeof AuthenticatedProcedimentosSlugRoute
}

const AuthenticatedProcedimentosRouteChildren: AuthenticatedProcedimentosRouteChildren =
  {
    AuthenticatedProcedimentosSlugRoute: AuthenticatedProcedimentosSlugRoute,
  }

const AuthenticatedProcedimentosRouteWithChildren =
  AuthenticatedProcedimentosRoute._addFileChildren(
    AuthenticatedProcedimentosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRouteWithChildren
  AuthenticatedDepartamentosRoute: typeof AuthenticatedDepartamentosRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRouteWithChildren
  AuthenticatedInstitucionalRoute: typeof AuthenticatedInstitucionalRouteWithChildren
  AuthenticatedNoticiasRoute: typeof AuthenticatedNoticiasRouteWithChildren
  AuthenticatedProcedimentosRoute: typeof AuthenticatedProcedimentosRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDepartamentoSlugRoute: typeof AuthenticatedDepartamentoSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRouteWithChildren,
  AuthenticatedDepartamentosRoute: AuthenticatedDepartamentosRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRouteWithChildren,
  AuthenticatedInstitucionalRoute: AuthenticatedInstitucionalRouteWithChildren,
  AuthenticatedNoticiasRoute: AuthenticatedNoticiasRouteWithChildren,
  AuthenticatedProcedimentosRoute: AuthenticatedProcedimentosRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDepartamentoSlugRoute: AuthenticatedDepartamentoSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SrcRoutesAuthenticatedColaboradoresRouteChildren {
  SrcRoutesAuthenticatedColaboradoresIdRoute: typeof SrcRoutesAuthenticatedColaboradoresIdRoute
}

const SrcRoutesAuthenticatedColaboradoresRouteChildren: SrcRoutesAuthenticatedColaboradoresRouteChildren =
  {
    SrcRoutesAuthenticatedColaboradoresIdRoute:
      SrcRoutesAuthenticatedColaboradoresIdRoute,
  }

const SrcRoutesAuthenticatedColaboradoresRouteWithChildren =
  SrcRoutesAuthenticatedColaboradoresRoute._addFileChildren(
    SrcRoutesAuthenticatedColaboradoresRouteChildren,
  )

interface SrcRoutesAuthenticatedDocumentosRouteChildren {
  SrcRoutesAuthenticatedDocumentosSlugRoute: typeof SrcRoutesAuthenticatedDocumentosSlugRoute
}

const SrcRoutesAuthenticatedDocumentosRouteChildren: SrcRoutesAuthenticatedDocumentosRouteChildren =
  {
    SrcRoutesAuthenticatedDocumentosSlugRoute:
      SrcRoutesAuthenticatedDocumentosSlugRoute,
  }

const SrcRoutesAuthenticatedDocumentosRouteWithChildren =
  SrcRoutesAuthenticatedDocumentosRoute._addFileChildren(
    SrcRoutesAuthenticatedDocumentosRouteChildren,
  )

interface SrcRoutesAuthenticatedInstitucionalRouteChildren {
  SrcRoutesAuthenticatedInstitucionalSlugRoute: typeof SrcRoutesAuthenticatedInstitucionalSlugRoute
}

const SrcRoutesAuthenticatedInstitucionalRouteChildren: SrcRoutesAuthenticatedInstitucionalRouteChildren =
  {
    SrcRoutesAuthenticatedInstitucionalSlugRoute:
      SrcRoutesAuthenticatedInstitucionalSlugRoute,
  }

const SrcRoutesAuthenticatedInstitucionalRouteWithChildren =
  SrcRoutesAuthenticatedInstitucionalRoute._addFileChildren(
    SrcRoutesAuthenticatedInstitucionalRouteChildren,
  )

interface SrcRoutesAuthenticatedNoticiasRouteChildren {
  SrcRoutesAuthenticatedNoticiasSlugRoute: typeof SrcRoutesAuthenticatedNoticiasSlugRoute
}

const SrcRoutesAuthenticatedNoticiasRouteChildren: SrcRoutesAuthenticatedNoticiasRouteChildren =
  {
    SrcRoutesAuthenticatedNoticiasSlugRoute:
      SrcRoutesAuthenticatedNoticiasSlugRoute,
  }

const SrcRoutesAuthenticatedNoticiasRouteWithChildren =
  SrcRoutesAuthenticatedNoticiasRoute._addFileChildren(
    SrcRoutesAuthenticatedNoticiasRouteChildren,
  )

interface SrcRoutesAuthenticatedProcedimentosRouteChildren {
  SrcRoutesAuthenticatedProcedimentosSlugRoute: typeof SrcRoutesAuthenticatedProcedimentosSlugRoute
}

const SrcRoutesAuthenticatedProcedimentosRouteChildren: SrcRoutesAuthenticatedProcedimentosRouteChildren =
  {
    SrcRoutesAuthenticatedProcedimentosSlugRoute:
      SrcRoutesAuthenticatedProcedimentosSlugRoute,
  }

const SrcRoutesAuthenticatedProcedimentosRouteWithChildren =
  SrcRoutesAuthenticatedProcedimentosRoute._addFileChildren(
    SrcRoutesAuthenticatedProcedimentosRouteChildren,
  )

interface SrcRoutesAuthenticatedRouteChildren {
  SrcRoutesAuthenticatedAdminRoute: typeof SrcRoutesAuthenticatedAdminRoute
  SrcRoutesAuthenticatedColaboradoresRoute: typeof SrcRoutesAuthenticatedColaboradoresRouteWithChildren
  SrcRoutesAuthenticatedDepartamentosRoute: typeof SrcRoutesAuthenticatedDepartamentosRoute
  SrcRoutesAuthenticatedDocumentosRoute: typeof SrcRoutesAuthenticatedDocumentosRouteWithChildren
  SrcRoutesAuthenticatedInstitucionalRoute: typeof SrcRoutesAuthenticatedInstitucionalRouteWithChildren
  SrcRoutesAuthenticatedNoticiasRoute: typeof SrcRoutesAuthenticatedNoticiasRouteWithChildren
  SrcRoutesAuthenticatedProcedimentosRoute: typeof SrcRoutesAuthenticatedProcedimentosRouteWithChildren
  SrcRoutesAuthenticatedIndexRoute: typeof SrcRoutesAuthenticatedIndexRoute
  SrcRoutesAuthenticatedDepartamentoSlugRoute: typeof SrcRoutesAuthenticatedDepartamentoSlugRoute
}

const SrcRoutesAuthenticatedRouteChildren: SrcRoutesAuthenticatedRouteChildren =
  {
    SrcRoutesAuthenticatedAdminRoute: SrcRoutesAuthenticatedAdminRoute,
    SrcRoutesAuthenticatedColaboradoresRoute:
      SrcRoutesAuthenticatedColaboradoresRouteWithChildren,
    SrcRoutesAuthenticatedDepartamentosRoute:
      SrcRoutesAuthenticatedDepartamentosRoute,
    SrcRoutesAuthenticatedDocumentosRoute:
      SrcRoutesAuthenticatedDocumentosRouteWithChildren,
    SrcRoutesAuthenticatedInstitucionalRoute:
      SrcRoutesAuthenticatedInstitucionalRouteWithChildren,
    SrcRoutesAuthenticatedNoticiasRoute:
      SrcRoutesAuthenticatedNoticiasRouteWithChildren,
    SrcRoutesAuthenticatedProcedimentosRoute:
      SrcRoutesAuthenticatedProcedimentosRouteWithChildren,
    SrcRoutesAuthenticatedIndexRoute: SrcRoutesAuthenticatedIndexRoute,
    SrcRoutesAuthenticatedDepartamentoSlugRoute:
      SrcRoutesAuthenticatedDepartamentoSlugRoute,
  }

const SrcRoutesAuthenticatedRouteWithChildren =
  SrcRoutesAuthenticatedRoute._addFileChildren(
    SrcRoutesAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ColaboradoresRoute: ColaboradoresRoute,
  DocumentosRoute: DocumentosRoute,
  InstitucionalRoute: InstitucionalRoute,
  LoginRoute: LoginRoute,
  NoticiasRoute: NoticiasRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  SrcRoutes_rootRoute: SrcRoutes_rootRoute,
  SrcRoutesAuthenticatedRoute: SrcRoutesAuthenticatedRouteWithChildren,
  SrcRoutesLoginRoute: SrcRoutesLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
